import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MenuBar from "@/components/MenuBar";
import { Separator } from "@/components/ui/separator";
import BackgroundDots from "@/components/Bgdots";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex items-center justify-between w-full flex-col p-8 min-h-screen">
          <div className={"w-full max-w-3xl my-4"}>
            <Navbar />
            <Separator className="w-full  my-5 rounded h-0.5" />
            <MenuBar />
            {children}
          </div>
        </main>
            <Footer />
      </body>
    </html>
  );
}
